--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring.data:
  redis:
    # 地址
    host: 43.139.142.207
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码(如没有密码请注释掉)
    password: 20040816Ywj
    username: default
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl.enabled: false
#    短信配置
aliyun:
  sms:
    sms-access-key-id: LTAI5tPJUvG9SibMtS2Tq1SN
    sms-access-key-secret: OeM2AM9GAgIfv7mLyxvgYWjkkHUrA1
    #签名名称
    sms-sign-name: 阿里云短信测试
    #短信模板信息
    sms-template-code: SMS_154950909
    sms-endpoint: dysmsapi.aliyuncs.com
#    oss配置
oss:
  endpoint: oss-accelerate.aliyuncs.com
  accessKeyId: LTAI5tPJUvG9SibMtS2Tq1SN
  accessKeySecret: OeM2AM9GAgIfv7mLyxvgYWjkkHUrA1
  bucketName: web-tilas-y

spring:
  datasource:
    url: jdbc:mysql://43.139.142.207:3306/timebank?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 20040816Ywj
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000

fabric:
  networkConnectionConfigPath: connection.json
  certificatePath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  privateKeyPath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
